package sv.edu.udb.www.entities;
// Generated 02-nov-2017 18:39:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Generos generated by hbm2java
 */
public class Generos  implements java.io.Serializable {


     private Integer idGenero;
     private String nombreGenero;
     private String descripcion;
     private Set libroses = new HashSet(0);

    public Generos() {
    }

	
    public Generos(String nombreGenero, String descripcion) {
        this.nombreGenero = nombreGenero;
        this.descripcion = descripcion;
    }
    public Generos(String nombreGenero, String descripcion, Set libroses) {
       this.nombreGenero = nombreGenero;
       this.descripcion = descripcion;
       this.libroses = libroses;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set libroses) {
        this.libroses = libroses;
    }




}


